# Generated by Django 4.1.7 on 2023-03-29 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0008_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_new_ad_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=255)),
                ('page_no', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('mode', models.CharField(max_length=30)),
                ('image_name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.company')),
            ],
            options={
                'db_table': 'add_new_ad_type',
            },
        ),
    ]
