# Generated by Django 4.1.7 on 2023-03-29 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
