# Generated by Django 4.1.7 on 2023-03-29 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cities', models.CharField(max_length=150)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.state')),
            ],
            options={
                'db_table': 'city',
            },
        ),
    ]
